<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Sanity Test suite" duration-ms="85" started-at="2018-09-12T13:13:21Z" finished-at="2018-09-12T13:13:21Z">
    <groups>
      <group name="A">
        <method signature="TestSkipDemo.testCode()[pri:0, instance:testNGDemo.TestSkipDemo@67b64c45]" name="testCode" class="testNGDemo.TestSkipDemo"/>
      </group> <!-- A -->
    </groups>
    <test name="Class Test Execution" duration-ms="85" started-at="2018-09-12T13:13:21Z" finished-at="2018-09-12T13:13:21Z">
      <class name="testNGDemo.TestSkipDemo2">
        <test-method status="SKIP" signature="testInAnotherClass()[pri:0, instance:testNGDemo.TestSkipDemo2@4411d970]" name="testInAnotherClass" duration-ms="0" depends-on-groups="A" started-at="2018-09-12T13:13:21Z" finished-at="2018-09-12T13:13:21Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestSkipDemo2.testInAnotherClass()[pri:0, instance:testNGDemo.TestSkipDemo2@4411d970] depends on not successfully finished methods in group "A"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestSkipDemo2.testInAnotherClass()[pri:0, instance:testNGDemo.TestSkipDemo2@4411d970] depends on not successfully finished methods in group "A"
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInAnotherClass -->
      </class> <!-- testNGDemo.TestSkipDemo2 -->
      <class name="testNGDemo.TestSkipDemo">
        <test-method status="PASS" signature="preconditions()[pri:0, instance:testNGDemo.TestSkipDemo@67b64c45]" name="preconditions" duration-ms="0" started-at="2018-09-12T13:13:21Z" finished-at="2018-09-12T13:13:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preconditions -->
        <test-method status="FAIL" signature="testCode()[pri:0, instance:testNGDemo.TestSkipDemo@67b64c45]" name="testCode" duration-ms="0" started-at="2018-09-12T13:13:21Z" depends-on-methods="testNGDemo.TestSkipDemo.preconditions" finished-at="2018-09-12T13:13:21Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [10] but found [5]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [10] but found [5]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at testNGDemo.TestSkipDemo.testCode(TestSkipDemo.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCode -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:testNGDemo.TestSkipDemo@67b64c45]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-09-12T13:13:21Z" finished-at="2018-09-12T13:13:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=tearDown status=SUCCESS method=TestSkipDemo.tearDown()[pri:0, instance:testNGDemo.TestSkipDemo@67b64c45] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:testNGDemo.TestSkipDemo@67b64c45]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-09-12T13:13:21Z" finished-at="2018-09-12T13:13:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=preconditions status=SUCCESS method=TestSkipDemo.preconditions()[pri:0, instance:testNGDemo.TestSkipDemo@67b64c45] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testNGDemo.TestSkipDemo@67b64c45]" name="tearDown" duration-ms="0" started-at="2018-09-12T13:13:21Z" finished-at="2018-09-12T13:13:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:testNGDemo.TestSkipDemo@67b64c45]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-09-12T13:13:21Z" finished-at="2018-09-12T13:13:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testCode status=FAILURE method=TestSkipDemo.testCode()[pri:0, instance:testNGDemo.TestSkipDemo@67b64c45] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- testNGDemo.TestSkipDemo -->
    </test> <!-- Class Test Execution -->
  </suite> <!-- Sanity Test suite -->
</testng-results>
